import './style.css';
import campaign from '../public/levels.json';
import shuffleLayouts from '../public/vehicle-shuffles.json';
import {vipIcon,arrangeIcon,changerIcon} from './booster-icons';
import {Simulation,makeLevel,MODELS,PALETTE,screen,type Level,type VehicleSpec} from './logic';
import {GameScene} from './scene';
import {GameAudio} from './audio';
import {gameViewport} from './viewport';

const game=document.querySelector<HTMLElement>('#game')!,canvas=document.querySelector<HTMLCanvasElement>('#scene')!,ui=document.querySelector<HTMLElement>('#ui')!;
const restartIcon='<svg viewBox="0 0 40 40" fill="none"><path d="M10 12a14 14 0 1 1-2 18" stroke="white" stroke-width="6" stroke-linecap="round"/><path d="M11 3 4 15l14 1" fill="white" stroke="white" stroke-linejoin="round" stroke-width="2"/></svg>';
const pauseIcon='<svg viewBox="0 0 40 40" fill="white"><rect x="9" y="5" width="7" height="30" rx="2"/><rect x="24" y="5" width="7" height="30" rx="2"/></svg>';
const lockIcon='<svg class="lock" viewBox="0 0 52 65"><path d="M12 29V19C12 0 40 0 40 19v10" fill="none" stroke="#d69924" stroke-width="9"/><path d="M13 28V18C13 3 39 3 39 18v10" fill="none" stroke="#ffe58a" stroke-width="5"/><rect x="4" y="25" width="44" height="36" rx="11" fill="#E9A82C"/><rect x="4" y="23" width="44" height="34" rx="11" fill="#FFD055"/><circle cx="26" cy="37" r="5" fill="#8c5322"/><path d="m23 39-1 9h8l-1-9" fill="#8c5322"/></svg>';
const hand='<svg viewBox="0 0 65 80"><path d="M27 67C11 57 7 45 11 40c3-4 9 5 13 7L17 17c-3-10 8-13 11-4l7 23c-1-8 8-9 10-1 2-7 10-5 11 3 8-3 12 5 10 13L57 72c-4 10-17 9-30-5Z" fill="#eef7fd" stroke="#92adc3" stroke-width="2.5"/></svg>';
type Save={level:number;unlocked:number;coins:number;sound:boolean;music:boolean};
const defaultSave:Save={level:1,unlocked:1,coins:100,sound:true,music:false};
let saved:Save={...defaultSave};try{const value=JSON.parse(localStorage.getItem('passenger-parking-v1')||'null');if(value)saved={...defaultSave,...value};}catch{}
saved.level=Math.max(1,Math.min(50,Number(saved.level)||1));saved.unlocked=Math.max(1,Math.min(50,Number(saved.unlocked)||1));
const store=()=>{try{localStorage.setItem('passenger-parking-v1',JSON.stringify(saved));}catch{}};
let view:GameScene;const audio=new GameAudio();let sim:Simulation;let levels:Level[]=campaign as Level[];let overlay:HTMLElement|null=null;let vipMode=false;let toastTimer=0;let highlightTimer=0;let highlightId=-1;let completeAwarded=false;let autoPaused=false;
function fit(){
  const vv=window.visualViewport,style=getComputedStyle(document.body);
  const inset=(side:string)=>parseFloat(style.getPropertyValue('--safe-'+side))||0;
  const layout=gameViewport(vv?.width||innerWidth,vv?.height||innerHeight,{left:inset('left'),right:inset('right'),top:inset('top'),bottom:inset('bottom')});
  game.style.width=layout.width+'px';game.style.height=layout.height+'px';game.style.left=(vv?.offsetLeft||0)+'px';game.style.top=(vv?.offsetTop||0)+'px';
  ui.style.transform=`translate(${layout.left}px,${layout.top}px) scale(${layout.scale})`;
  const winWidth=Math.max(1,layout.width-inset('left')-inset('right')-32),winHeight=Math.max(1,layout.height-inset('top')-inset('bottom')-32);
  game.style.setProperty('--win-unit',Math.min(winWidth/500,winHeight/700,1)+'px');
  view?.resize(layout);
}
let fitQueued=false;
function scheduleFit(){if(fitQueued)return;fitQueued=true;requestAnimationFrame(()=>{fitQueued=false;fit();});}
window.addEventListener('resize',scheduleFit);window.visualViewport?.addEventListener('resize',scheduleFit);window.visualViewport?.addEventListener('scroll',scheduleFit);fit();
function button(id:string,label:string,content:string,style=''){return `<button id="${id}" aria-label="${label}" ${style}>${content}</button>`;}
function buildHUD(){ui.innerHTML=`${button('restart','Restart level',restartIcon,'class="hud-button"')}${button('pause','Pause game',pauseIcon,'class="hud-button"')}${button('level','Choose level',`Level ${sim.level.id}`,'class="level-label"')}<span class="vip-mark">VIP</span>${[0,1,2,3,4,5,6,7].map(i=>`<span class="bay-label" id="bay-${i}" style="left:${73+i*59}px;display:none"></span>`).join('')}${[5,6,7].map(i=>button(`extra-${i}`,'Unlock extra boarding bay','+ ',`class="plus-mark" style="left:${73+i*59}px"`)).join('')}<button id="vip" class="booster" style="left:60px" aria-label="VIP booster">${sim.level.id<4?lockIcon:vipIcon}<span class="booster-label">${sim.level.id<4?'Level 4':'VIP'}</span>${sim.level.id>=4?`<span class="badge ${sim.vipUses>=2?'used':''}">${2-sim.vipUses}</span>`:''}</button><button id="arrange" class="booster" style="left:232px" aria-label="Arrange passengers">${sim.level.id<8?lockIcon:arrangeIcon}<span class="booster-label">${sim.level.id<8?'Level 8':'Arrange'}</span>${sim.level.id>=8?`<span class="badge ${sim.arrangeUses>=1?'used':''}">${1-sim.arrangeUses}</span>`:''}</button><button id="changer" class="booster" style="left:404px" aria-label="Bus Changer">${sim.level.id<13?lockIcon:changerIcon}<span class="booster-label">${sim.level.id<13?'Level 13':'Bus Changer'}</span>${sim.level.id>=13?`<span class="badge ${sim.shuffleUses?'used':''}">${1-sim.shuffleUses}</span>`:''}</button><div id="toast" role="status" class="toast hidden"></div><div id="pointer" class="hand" style="display:none">${hand}</div><div id="ring" class="hint-ring" style="display:none"></div>${sim.level.id===1?'<div id="tutorial" class="tutorial">Tap the vehicle to<br>match the passengers</div>':''}`;
  document.getElementById('restart')!.onclick=()=>confirmRestart();document.getElementById('pause')!.onclick=()=>pause();document.getElementById('level')!.onclick=()=>levelPicker();
  document.getElementById('vip')!.onclick=()=>useVip();document.getElementById('arrange')!.onclick=()=>useArrange();document.getElementById('changer')!.onclick=()=>useChanger();
  for(let i=5;i<8;i++)document.getElementById(`extra-${i}`)!.onclick=()=>extraBay(i);
}
function startLevel(id:number){if(overlay){overlay.remove();overlay=null;}vipMode=false;completeAwarded=false;sim=new Simulation(structuredClone(levels[id-1]||makeLevel(id)));view.load(sim);saved.level=id;store();buildHUD();highlightId=sim.level.solution[0];highlightTimer=id===1?999:0;audio.enabled=saved.sound;audio.music=saved.music;view.setQuality();}
function toast(text:string){const el=document.getElementById('toast')!;el.textContent=text;el.classList.remove('hidden');toastTimer=1.8;}
function modal(content:string,klass=''){if(overlay)overlay.remove();overlay=document.createElement('section');overlay.className='modal '+klass;overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.innerHTML=content;(klass==='win'?game:ui).appendChild(overlay);return overlay;}
function resume(){overlay?.remove();overlay=null;sim.paused=false;audio.unlock();}
function pause(){if(sim.state!=='playing')return;sim.paused=true;audio.play('tap');const el=modal(`<div class="panel"><h2>Paused</h2><div class="setting">Sound<button id="sound-toggle" aria-label="Toggle sound" class="toggle ${saved.sound?'on':''}"></button></div><div class="setting">Music<button id="music-toggle" aria-label="Toggle music" class="toggle ${saved.music?'on':''}"></button></div><button id="resume" class="green-button">Continue</button><button id="pause-restart" class="gold-button">Restart</button></div>`);
  el.querySelector('#resume')!.addEventListener('click',resume);el.querySelector('#pause-restart')!.addEventListener('click',()=>startLevel(sim.level.id));
  el.querySelector('#sound-toggle')!.addEventListener('click',e=>{saved.sound=!saved.sound;audio.enabled=saved.sound;(e.currentTarget as HTMLElement).classList.toggle('on',saved.sound);store();audio.play('tap');});
  el.querySelector('#music-toggle')!.addEventListener('click',e=>{saved.music=!saved.music;audio.music=saved.music;(e.currentTarget as HTMLElement).classList.toggle('on',saved.music);store();});
}
function confirmRestart(){sim.paused=true;audio.play('tap');const el=modal('<div class="panel"><h2>Restart?</h2><p>Try this level again from the beginning.</p><button id="yes" class="gold-button">Restart</button><button id="no" class="green-button">Keep playing</button></div>');el.querySelector('#yes')!.addEventListener('click',()=>startLevel(sim.level.id));el.querySelector('#no')!.addEventListener('click',resume);}
function levelPicker(){sim.paused=true;const el=modal(`<div class="panel"><h2>Choose a level</h2><div class="level-grid">${Array.from({length:50},(_,i)=>`<button class="level-cell ${sim.level.id===i+1?'current':''}" data-level="${i+1}" ${i+1>saved.unlocked?'disabled':''}>${i+1>saved.unlocked?'🔒':i+1}</button>`).join('')}</div><button id="back" class="green-button">Back</button></div>`);el.querySelectorAll<HTMLButtonElement>('[data-level]').forEach(b=>b.onclick=()=>startLevel(Number(b.dataset.level)));el.querySelector('#back')!.addEventListener('click',resume);}
function useVip(){audio.play('tap');if(sim.level.id<4){toast('VIP unlocks at Level 4');return;}if(sim.vipUses>=2){toast('VIP used twice this level');return;}if(sim.bays[0]!==null){toast('The VIP spot is occupied');return;}if(sim.paused||sim.state!=='playing'||sim.shuffleClock>0||vipMode)return;vipMode=true;const layer=document.createElement('div');layer.className='vip-selection';layer.id='vip-selection';layer.innerHTML='<div class="tutorial">Select a Vehicle for the<br>VIP Spot</div><button id="cancel-vip">Cancel</button>';ui.appendChild(layer);layer.querySelector('button')!.onclick=()=>{vipMode=false;layer.remove();};}
function useArrange(){audio.play('tap');if(sim.level.id<8){toast('Arrange unlocks at Level 8');return;}if(sim.arrangeUses){toast('Passenger shuffle already used');return;}if(vipMode||sim.paused||sim.state!=='playing')return;if(sim.arrange()){buildHUD();toast('Circle and waiting passengers shuffled');}else toast('No waiting colors to exchange right now');}
function useChanger(){audio.play('tap');if(sim.level.id<13){toast('Bus Changer unlocks at Level 13');return;}if(sim.shuffleUses){toast('Bus Changer already used');return;}if(vipMode||sim.paused||sim.state!=='playing')return;const layout=(shuffleLayouts as Record<string,VehicleSpec[]>)[sim.level.id];if(layout&&sim.shuffleVehicles(layout)){view.animateShuffle();highlightTimer=0;buildHUD();toast('Vehicle positions shuffled');}else toast('Wait for moving vehicles, then try again');}
function extraBay(index:number){if(sim.extraBays>=1){toast('Only one extra spot per level');return;}if(sim.paused||sim.state!=='playing')return;audio.play('tap');sim.paused=true;const el=modal('<div class="panel"><h2>Extra spot</h2><p>Open another boarding spot for this level.</p><button id="unlock" class="green-button">Unlock free</button><button id="back" class="under-button">Back</button></div>');el.querySelector('#unlock')!.addEventListener('click',()=>{sim.unlockExtraBay(index);resume();updateUI(0);});el.querySelector('#back')!.addEventListener('click',resume);}
function win(){if(completeAwarded)return;completeAwarded=true;document.getElementById('tutorial')?.remove();saved.coins+=20;saved.unlocked=Math.max(saved.unlocked,Math.min(50,sim.level.id+1));store();audio.play('win');
  const el=modal(`<div class="fireworks" aria-hidden="true">${Array.from({length:22},(_,i)=>`<span class="star" style="left:${(i*37)%100}%;top:${10+(i*13)%75}%;animation-delay:${i*.09}s">✦</span>`).join('')}</div><div class="win-safe"><div class="win-content"><div class="victory-copy"><div class="victory-kicker">LEVEL ${sim.level.id} COMPLETE</div><h1 id="victory-title" class="great-job"><span>Great</span><span>Job!</span></h1><p>Every passenger is on their way!</p></div><div class="win-actions"><button id="next" class="gold-button">${sim.level.id<50?'Next':'All clear!'}</button></div></div></div>`,'win');el.setAttribute('aria-labelledby','victory-title');el.querySelector('#next')!.addEventListener('click',()=>{audio.play('tap');if(sim.level.id<50)startLevel(sim.level.id+1);else levelPicker();});
}
function fail(){audio.play('fail');const el=modal(`<div class="coin-counter">${saved.coins}</div><div class="panel"><h2>Out of Spots</h2><p>${sim.extraBays?'Clear all parked buses and continue!':'Clear all parked buses<br>and unlock 1 extra spot!'}</p><div class="button-row"><button class="gold-button" id="paid-recover">$ 900</button><button class="green-button" id="free-recover">▶ Free</button></div><button id="fail-restart" class="under-button">Restart</button></div>`);const recover=()=>{sim.recover();overlay?.remove();overlay=null;};el.querySelector('#paid-recover')!.addEventListener('click',()=>{if(saved.coins<900){const p=el.querySelector('p')!;p.textContent='Not enough coins. Use the free option.';return;}saved.coins-=900;store();recover();});el.querySelector('#free-recover')!.addEventListener('click',recover);el.querySelector('#fail-restart')!.addEventListener('click',()=>startLevel(sim.level.id));}
function updateUI(dt:number){for(let i=0;i<8;i++){const badge=document.getElementById('bay-'+i)!;const id=sim.bays[i],car=id===null?null:sim.cars[id];const show=car&&(car.status==='boarding'||car.status==='travel');badge.style.display=show?'block':'none';if(show){badge.textContent=String(car.remaining);badge.style.background=PALETTE[car.spec.color];}if(i>4)document.getElementById('extra-'+i)!.style.display=sim.extraBays>=1?'none':'block';}
  if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)document.getElementById('toast')?.classList.add('hidden');}
  const pointer=document.getElementById('pointer')!,ring=document.getElementById('ring')!;
  if(highlightTimer>0&&sim.state==='playing'&&!sim.paused){highlightTimer-=dt;if(sim.cars[highlightId]?.status!=='yard'&&sim.level.id===1)highlightId=sim.level.solution.find(id=>sim.cars[id].status==='yard')??-1;const car=sim.cars[highlightId];if(car?.status==='yard'){const p=screen({x:car.spec.x,z:car.spec.z,y:.65});pointer.style.display='block';pointer.style.left=p.x+10+'px';pointer.style.top=p.y-8+'px';const dim=MODELS[car.spec.model];ring.style.display='block';ring.style.left=p.x-dim.width*car.spec.scale*27+'px';ring.style.top=p.y-dim.length*car.spec.scale*25+'px';ring.style.width=dim.width*car.spec.scale*54+'px';ring.style.height=dim.length*car.spec.scale*50+'px';ring.style.transform=`rotate(${car.spec.yaw}rad)`;}else{pointer.style.display=ring.style.display='none';document.getElementById('tutorial')?.remove();}}else pointer.style.display=ring.style.display='none';
}
document.addEventListener('visibilitychange',()=>{if(document.hidden){if(sim?.state==='playing'&&!sim.paused){sim.paused=true;autoPaused=true;}audio.suspend();}else if(autoPaused){autoPaused=false;pause();}});
async function init(){try{
  view=new GameScene(canvas);view.onVehicle=id=>{audio.unlock();if(sim.dispatch(id,vipMode)){if(vipMode){vipMode=false;document.getElementById('vip-selection')?.remove();buildHUD();}}};
  const devLevel=import.meta.env.DEV?Number(new URLSearchParams(location.search).get('level')):0;
  startLevel(devLevel>=1&&devLevel<=50?devLevel:saved.level);document.getElementById('loading')!.remove();fit();
  let last=performance.now(),accumulator=0;
  view.engine.runRenderLoop(()=>{const now=performance.now();const raw=Math.min((now-last)/1000,.1);last=now;const dt=sim.paused?0:raw;accumulator+=dt;while(accumulator>=1/60){sim.tick(1/60);accumulator-=1/60;}
    for(const e of sim.events){if(e.type==='blocked'){view.nudge(e.vehicle!);audio.play('blocked');}else if(e.type==='no-space'){toast('No spots available');audio.play('blocked');}else if(e.type==='full'){view.burst(e.vehicle!);audio.play('full');}else if(e.type==='win')win();else if(e.type==='fail')fail();else audio.play(e.type);}sim.events.length=0;
    view.update(dt);view.render();updateUI(dt);audio.tick(raw,sim.paused||sim.state!=='playing');
  });
  if(import.meta.env.DEV)(window as unknown as {__game:unknown}).__game={get sim(){return sim;},view,startLevel,win,fail,audio,save:saved};
}catch(error){console.error(error);const loading=document.getElementById('loading')!;loading.innerHTML='<p style="padding:24px;text-align:center">The 3D scene could not start.<br>Try updating your browser, then reload.</p><button style="padding:12px 25px;border-radius:12px" onclick="location.reload()">Reload</button>';}}
void init();
