import {test} from 'node:test';
import {readFileSync} from 'node:fs';
const alternates=JSON.parse(readFileSync(new URL('../public/vehicle-shuffles.json',import.meta.url),'utf8'));
import assert from 'node:assert/strict';
import {makeLevel,Simulation,MODELS,COLORS,canExit,overlaps,blocks,footprint,screen,type VehicleSpec} from '../src/logic.ts';
const campaign=JSON.parse(readFileSync(new URL('../public/levels.json',import.meta.url),'utf8'));
test('post-ten demand rises every level, exported levels stay in sync, and compact yards stay on screen',()=>{
  let demand=campaign[9].passengers.length,count=campaign[9].vehicles.length;
  for(let id=1;id<=50;id++){
    const l=makeLevel(id);assert.deepEqual(l,campaign[id-1],`stale exported level ${id}`);
    for(const v of l.vehicles)for(const corner of footprint(v)){const p=screen(corner);assert(p.x>=40&&p.x<=550&&p.y>=616&&p.y<=1090,`yard bounds ${id}/${v.id}`);}
    if(id>10){assert(l.passengers.length>demand,`demand did not rise at ${id}`);assert(l.vehicles.length>=count);demand=l.passengers.length;count=l.vehicles.length;}
  }
});
test('all 50 deterministic layouts are disjoint, balanced and have legal constructive witnesses',()=>{
  for(let id=1;id<=50;id++){const l=makeLevel(id);assert.deepEqual(l,makeLevel(id));assert.equal(l.solution.length,l.vehicles.length);for(let a=0;a<l.vehicles.length;a++)for(let b=a+1;b<l.vehicles.length;b++)assert.equal(overlaps(l.vehicles[a],l.vehicles[b],0),false,`overlap level ${id}: ${a}/${b}`);
    for(const color of COLORS)assert.equal(l.vehicles.filter(v=>v.color===color).reduce((s,v)=>s+MODELS[v.model].capacity,0),l.passengers.filter(c=>c===color).length);
    const pending=[...l.vehicles];for(const vId of l.solution){const v=pending.find(v=>v.id===vId)!;assert(canExit(v,pending),`witness ${id}/${vId}`);pending.splice(pending.indexOf(v),1);}}
});
test('all 50 levels complete through real circulation, reservations and boarding without boosters',()=>{
  for(let id=1;id<=50;id++){const s=new Simulation(makeLevel(id));let index=0,steps=0;while(s.state==='playing'&&steps++<150000){const next=s.level.solution[index];if(next!==undefined&&s.cars.every(c=>c.status!=='travel'&&c.status!=='boarding'&&c.status!=='leaving')){assert(s.dispatch(next));index++;}s.tick(.1);s.events.length=0;}assert.equal(s.state,'win',`level ${id} failed after ${steps}`);assert.equal(s.unserved,0);assert(s.cars.every(c=>c.remaining===0&&c.reserved===0));}
});
test('bay reservations reject duplicate dispatch and survive pause without advancing',()=>{const s=new Simulation(makeLevel(1));const id=s.level.solution[0];assert(s.dispatch(id));assert.equal(s.dispatch(id),false);const t=s.time;s.paused=true;s.tick(.1);assert.equal(s.time,t);assert.equal(s.bays.filter(v=>v!==null).length,1);});
test('swept vehicle width detects a blocker away from its center ray',()=>{const a:VehicleSpec={id:0,x:0,z:0,yaw:0,scale:1,model:'bus',color:'blue'};const b:VehicleSpec={...a,id:1,x:.8,z:3,model:'car'};assert(blocks(a,b));assert(!blocks(a,{...b,x:2}));});
test('recovery consumes matching passengers exactly once and releases the occupied bays',()=>{const s=new Simulation(makeLevel(4));const rescued=s.cars.slice(0,4);for(let i=0;i<4;i++){rescued[i].status='boarding';rescued[i].bay=i+1;s.bays[i+1]=rescued[i].spec.id;}s.state='fail';const before=s.unserved,capacity=rescued.reduce((n,c)=>n+c.remaining,0);s.recover();assert.equal(s.extraBays,1);assert.equal(s.unserved,before-capacity);assert(rescued.every(c=>c.remaining===0&&c.status==='leaving'));for(let i=0;i<23;i++)s.tick(.1);assert(rescued.every(c=>c.status==='gone'));assert.equal(s.bays.filter(b=>b!==null).length,0);});

test('only one additional bay can be unlocked, including repeated recovery',()=>{const s=new Simulation(makeLevel(1));assert(s.unlockExtraBay());assert(!s.unlockExtraBay());s.state='fail';s.recover();assert.equal(s.extraBays,1);s.state='fail';s.recover();assert.equal(s.extraBays,1);});
test('twelve connected passengers launch in one continuous stream, not separate four-person batches',()=>{const s=new Simulation(makeLevel(1));for(const p of s.people)p.color=p.slot<12?'blue':'red';const c=s.cars.find(c=>c.spec.color==='blue')!;c.status='boarding';c.bay=1;s.bays[1]=c.spec.id;s.phase=.23;s.tick(.08);const running=s.people.filter(p=>p.state==='running');assert.equal(running.length,12);assert.equal(c.reserved,12);assert.equal(new Set(running.map(p=>p.clock)).size,12);for(let i=0;i<30;i++)s.tick(.025);assert.equal(c.remaining,28);});
test('contiguous circle vacancies admit a continuous waiting stream from the correct feeder',()=>{const s=new Simulation(makeLevel(2));const side=s.feedSideAt(s.feedIndex),groupColor=s.level.passengers[s.feedIndex];let rows=0;for(let i=s.feedIndex;i<s.level.passengers.length&&s.feedSideAt(i)===side&&s.level.passengers[i]===groupColor&&rows<3;i+=4)rows++;assert.equal(rows,3);for(let slot=0;slot<12;slot++){s.people[s.slots[slot]!].state='boarded';s.slots[slot]=null;}s.phase=.876;s.tick(.04);const entering=s.people.filter(p=>p.state==='entering');assert.equal(entering.length,12);assert(entering.every(p=>p.feedSide===side));assert.equal(new Set(entering.map(p=>p.clock)).size,12);});
test('full vehicle stays in its own spot during the 1.5 second celebration',()=>{const s=new Simulation(makeLevel(1)),c=s.cars[0];c.status='leaving';c.bay=1;c.remaining=0;s.bays[1]=0;for(let i=0;i<15;i++)s.tick(.1);assert.equal(c.status,'leaving');assert.equal(s.bays[1],0);for(let i=0;i<8;i++)s.tick(.1);assert.equal(c.status,'gone');assert.equal(s.bays[1],null);});
test('Arrange preserves monochrome four-person rows and total colors',()=>{const s=new Simulation(makeLevel(8));s.cars[0].status='boarding';const count=()=>COLORS.map(color=>s.people.filter(p=>p.color===color).length+s.level.passengers.slice(s.feedIndex).filter(p=>p===color).length);const before=count();s.arrange();assert.deepEqual(count(),before);for(let slot=0;slot<s.slots.length;slot+=4){const colors=s.slots.slice(slot,slot+4).map(id=>s.people[id!].color);assert(colors.every(c=>c===colors[0]));}for(let i=s.feedIndex;i<s.level.passengers.length;i+=4)assert(s.level.passengers.slice(i,i+4).every(c=>c===s.level.passengers[i]));});

test('VIP is limited to two successful uses per level and cannot be refilled by recovery',()=>{const s=new Simulation(makeLevel(4));assert(s.dispatch(0,true));assert(!s.dispatch(1,true));assert.equal(s.vipUses,1);s.cars[0].status='gone';s.bays[0]=null;assert(s.dispatch(1,true));s.cars[1].status='gone';s.bays[0]=null;assert(!s.dispatch(2,true));s.state='fail';s.recover();assert(!s.dispatch(2,true));assert.equal(s.vipUses,2);assert.equal(new Simulation(makeLevel(4)).vipUses,0);assert(!new Simulation(makeLevel(1)).dispatch(0,true));});
test('passenger shuffle exchanges waiting and circle colors once even with no boarding vehicles',()=>{const s=new Simulation(makeLevel(8));const before=s.people.map(p=>p.color);assert(s.arrange());assert.notDeepEqual(s.people.map(p=>p.color),before);assert.equal(s.arrangeUses,1);const after=JSON.stringify(s.people);assert(!s.arrange());assert.equal(JSON.stringify(s.people),after);s.state='fail';s.recover();assert(!s.arrange());assert(!new Simulation(makeLevel(4)).arrange());});
test('all 38 Bus Changer layouts move every yard vehicle and remain solvable, with a single-use limit',()=>{for(let id=13;id<=50;id++){const s=new Simulation(makeLevel(id)),before=s.cars.map(c=>({...c.spec}));assert(s.shuffleVehicles(alternates[id]));assert.equal(s.shuffleUses,1);assert(s.cars.every((c,i)=>c.spec.x!==before[i].x||c.spec.z!==before[i].z));assert(!s.shuffleVehicles(alternates[id]));assert(!s.dispatch(s.level.solution[0]));let next=0,steps=0;while(s.state==='playing'&&steps++<150000){if(s.shuffleClock===0&&s.cars.every(c=>!['travel','boarding','leaving'].includes(c.status))&&s.level.solution[next]!==undefined){assert(s.dispatch(s.level.solution[next++]));}s.tick(.1);s.events.length=0;}assert.equal(s.state,'win',`shuffled level ${id}`);assert.equal(s.unserved,0);}});
test('Bus Changer preserves occupied stands and vehicle identity after partial play',()=>{const s=new Simulation(makeLevel(13)),boarding=s.cars[s.level.solution[0]],gone=s.cars[s.level.solution[1]];boarding.status='boarding';boarding.bay=1;s.bays[1]=boarding.spec.id;gone.status='gone';const before={...boarding.spec};assert(s.shuffleVehicles(alternates[13]));assert.deepEqual(boarding.spec,before);assert.equal(boarding.status,'boarding');assert.equal(s.bays[1],boarding.spec.id);assert.equal(gone.status,'gone');assert(s.cars.every(c=>c.remaining===MODELS[c.spec.model].capacity));});
